# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '-c Release'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    arguments: '-r win10-x64 --output publish_output'
    publishWebProjects: false
    modifyOutputPath: true
    zipAfterPublish: false

- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/windows.zip"

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/windows.zip'
    name: 'drop'

- task: GitHubRelease@0
  inputs:
    gitHubConnection: danielscholl
    repositoryName: '$(Build.Repository.Name)'
    tagSource: manual
    tag: $(Build.BuildNumber)      
    assets: |
         $(System.DefaultWorkingDirectory)/windows.zip
